# 请不要删除任何双引号！！！

[[User]]
[User.Cookie]
yxktml                 = "*************************"
remember_student_key   = "*************************"
remember_student_value = "*************************"
[User.Postdata]
# 签到位置
v = ""
# 您是否在校
# 0: 是 1: 否
q = "1"
# 学生身份
# 0: 本科生 1: 硕士生 2: 博士生 3: 新联学院学生 4: 预科生 5: 成教生 6: 留学生
z = "0"
# 接触人群中是否有进口冷链食品、口岸直接接触进口货物、隔离场所、交通运输工具等特殊行业从业人员
# 0: 有 1: 无
x = "1"
# 当前位置是否在中高风险区
# 0: 是 1: 否
w = "1"
# 是否接种过疫苗
# 0: 是 1: 否
a = "1"
# 今日体温（腋下温度）
b = "36.5"
# 是否有症状
# 0: 是 1: 否
c = "1"
# 是否发热（37.3度及以上）
# 0: 是 1: 否
d = "1"
# 是否被确诊为新型冠状病毒肺炎病例
# 0: 是 1: 否
e = "1"
# 是否是高度疑似新型冠状病毒肺炎人员
# 0: 是 1: 否
f = "1"
# 若高度疑似，具体隔离措施为
# 0: 是 1: 否
g = ""
# 本人电话
r = "***********"
# 紧急联系人姓名
s = "***"
# 紧急联系人手机号
t = ""
# 您需要学校提供跟此次疫情相关的协助说明
u = "无"
[User.Mail]
# qq邮箱
username = "**********@qq.com"
# qq邮箱授权码
password = "*************"
